### ISSUE TITLE
ch.olsen?

### ISSUE THREAD

**Issue by mbarszcz** [AntonVonGolub/Code#1]
Hello,

In code.java there's a bunch of imports from ch.olsen.products and routes. Is it possible for me to get access to those libraries?

Thanks

**Comment by jbglattfelder** [comment]
Hi there,

Thanks for you inquiry.

So, the ch.olsen packages literally have no impact on the code anymore. The references will be removed soon.

Kind regards,
james

**Comment by Sajam** [comment]
+1

**Comment by himanshusanghi** [comment]
Hi,

From what I see the code still uses the ch.olsen.products and ch.olsen.routes. 
Could you please share the link of the code that does not use the ch.olsen packages.

Thanks

**Comment by jbglattfelder** [comment]
You can just delete the lines with ch.olsen.* references...
