### ISSUE TITLE
Liquidity indicator

### ISSUE THREAD

**Issue by gsevans** [AntonVonGolub/Code#14]
First - thank you for publishing your work on scaling laws and trading models - it is quite amazing. I have two questions for you on the java code:
(i) LocalLiquidity uses parameters alpha and alpha weight that don't appear in equations (2) - (6) in the alpha engine paper. Could you please explain what alpha and alpha weight represent?
(ii) In calculating the surprise values and subsequent liquidity values in LocalLiquidity I can't see how the probability of K state transitions for a price trajectory in a time interval [0,T] is explicitly considered. Can you please clarify?

**Comment by KhaledYassin** [comment]
> First - thank you for publishing your work on scaling laws and trading models - it is quite amazing. I have two questions for you on the java code:
> (i) LocalLiquidity uses parameters alpha and alpha weight that don't appear in equations (2) - (6) in the alpha engine paper. Could you please explain what alpha and alpha weight represent?
> (ii) In calculating the surprise values and subsequent liquidity values in LocalLiquidity I can't see how the probability of K state transitions for a price trajectory in a time interval [0,T] is explicitly considered. Can you please clarify?

Hello! 

(i) Alpha and alpha weight are used in numerically approximating the mean surprises over K transitions. You can do without them depending on the method you choose for computing the mean.  
(ii) The time interval [0,T] is the interval over which we observe K transition and so it is not a fixed interval. 

Hope this helps.

**Comment by gsevans** [comment]
Thank you I think that helps but leads me to a couple of other questions: Why would you numerically approximate rather than use the method described in the papers? And, if the probability of a transition from DC to DC is approximately 0.63 and the probability of transition from OS to DC is also 0.63 why isn't the probability of K state transitions modelled as a binomial distribution? And finally is there an optimal value for K?

**Comment by KhaledYassin** [comment]
(i) The method described in the paper doesn't delve into how the mean is being calculated. You have the discretion in choosing how to estimate the mean. 
(ii) Yes it is indeed a binomial distribution which converges to a normal distribution for a large enough K as per the central limit theorem. 
(iii) The optimal choice of K depends on the context. For instance, what are you optimizing with respect to? This is an additional element that requires for which you have the discretion to choose.
