### ISSUE TITLE
Testing on XAUUSD (Gold)?

### ISSUE THREAD

**Issue by mailfilter888** [AntonVonGolub/Code#15]
Thank you for your work. I have tested your theory on forex pairs and had success similar to those mentioned in Figure 1 of the article (eg NZDJPY being a profitable pair). I have also tested this on gold starting 2007 to 2017. XAUUSD failed tests as compared to forex pairs. Had you done any testing on XAUUSD or could you try and let the community know your findings? Thank you.

**Comment by jbglattfelder** [comment]
Thank you for your interest in our work. Could you please explain a bit what you mean by "failed tests" for XAUUSD?

**Comment by mailfilter888** [comment]
Apologies, I mean it blew the account in 2011 as a result of too high a drawdown. I started with $1m. The largest drawdown using FX was around 1.0 - 1.8% for a similar back test period. Gold started at around $600 in 2007 then was around $1,900 in 2011 - this is a possible cause as the change in price was simply too much. It should be noted that runners in my programming end deltas at 100%. Is it intended that delta up/down exceed 100%?

**Comment by jbglattfelder** [comment]
The process of skewing (Section 3.6 in the "Alpha Engine" paper, i.e., dStarUp/Down in the code) is the mechanism that can increase or decrease thresholds. It is a function of the inventory. A simple implementation is to define a minimum (maximum) cumulative position size and then increase (decrease) the deltas of newly initialized coastline traders (e.g., double or halve). This should be done separately for long and short positions.

Regarding the XAU/USD, we have actually seen very good results for this instrument for a time period we tested between early 2000 and 2013. Indeed, even during problematic times (S&p500 quant meltdown, financial crisis, and flash crash; de-pegging of Swiss Franc; quantitative easing USD/JPY) the models performed well...
