### ISSUE TITLE
Node.js porting

### ISSUE THREAD

**Issue by albertosantini** [AntonVonGolub/Code#16]
I open this issue only to announce I ported the Alpha Engine to Node.js: https://github.com/albertosantini/argo-trading-plugin-dc.

Thank you a lot for your efforts based on IE.

**Comment by jbglattfelder** [comment]
Dear @albertosantini, wow thank you very much for this awesome resource:)

Kind regards,
james

**Comment by albertosantini** [comment]
Well, a lot of years ago I read "An Introduction to High-Frequency Finance" and I understood DC/OS events are a powerful tool. Playing with the code following those guidelines, it is a pleasure.

You deserve a great thanks.
