### ISSUE TITLE
Why multiple agents of same order type?

### ISSUE THREAD

**Issue by DaveAndersonCo** [AntonVonGolub/Code#17]
Hi,

I couldn't find the reason behind having multiple agents with different threshold for the same type of orders. Suppose that after some kind of research we find out that the certain threshold applies best to a currency like "AUD_CAD". Let's assume that 0.02 has been profitable for Buy and 0.03 for Sell based on historical research on this currency. Wouldn't be logical to have only one coastlinetrader for buy and one coaslinetrader for sell with these thresholds?

I see that the source code example uses multiple coastlinetraders with different thresholds. Is there a reason for that?

Regards,
Dave

**Comment by jbglattfelder** [comment]
Hi Dave,

What you are suggesting is an interesting adaptation of the framework. For us, intrinsic time is a foundational guiding principle. It is naturally defined for a range of thresholds, which are related via scaling laws. We believe that utilizing more than one threshold allows for more information to be extracted from the market and processed.

You mention the idea of asymmetric thresholds. We implemented a variant of this by introducing upward and downward thresholds which are skewed as a function of a trend proxy.

There are many ways this framework can be extended or adapted. Your intuition is probably the best guide to successfully explore this terrain.

Kind regards,
james

**Comment by DaveAndersonCo** [comment]
Thanks James.
