### ISSUE TITLE
Confusion about code.java not supporting trading model

### ISSUE THREAD

**Issue by DaveAndersonCo** [AntonVonGolub/Code#18]
Hi,

First I want to say that I appreciate your effort to make such examples.

And second...
I'm confused with some text inside the code.java example and differences with the LimitOrder example. Would you mind explain more about their differences. Because it seems to me that the only differences between these two examples are a few TODO's which have been implemented in the LimitOrder and putting Limit order type instead of instant market order type.

Are there any other differences which make code.java 'not supporting trading model' as you mentions in readme section?

Regards,
Dave

**Comment by jbglattfelder** [comment]
Hi David,

Thank you for your interest.

code.java is intended to give the reader a top-level overview of how the trading model algorithm functions, omitting implementation details, and inspire their own implementation. Hence the TODOS.

The LimitOrders directory contains such an implementation, also described in the "Alpha Engine" paper. This is the version to go with if you want to get a trading model up and running ASAP.

Regards,
james

**Comment by DaveAndersonCo** [comment]
Thanks James.
