### ISSUE TITLE
Question about order closing

### ISSUE THREAD

**Issue by pouet300** [AntonVonGolub/Code#19]
Hello,

Many thanks for your paper and sharing your work on github ;-)
I really like your ideas.
I'm testing it, trying to make it work with my own backtesting framework, with minimal changes.

So far, I'm launching only one CoastlineTrader with delta = 0.0005 for long positions.

My assumptions and understanding of your implementation is that 
- You have at the same time opposite positions on the same market but coming from different agents / deltas.
- The position.s (limit order impl.) of one agent is closed when a given profit is reached by making a market order of volume of all disbalanced orders
- When a agent in buying mode (for example) decascades, a sell limit order is made in order to close some of the previous buy (eventually taking a loss)

Is that correct or does the sell limit order force the position in the opposite direction so that an agent in buy mode could also open positions in both directions ? The methods makeBuyFilled and makeSellFilled take the profit and remove the orders from the disbalanced orders so I don't think a same agent manages positions in opposite directions but I just wanted to be 100% sure.

My question is: how do you ensure that you won't close the positions managed by another agent?
Maybe my question is naive and linked to my broker... But I don't have the possibility to make the matching of the position myself. Either I close *one* particular position, or I close many by compensating existing positions but my brocker maximizes the profit when I do so and picks the positions opened at a lower price if closing long and the opposite for short.

In real-world, do you use the "compensatedOrders" list to make sure you close the proper positions?

Thank you in advance,

**Comment by jbglattfelder** [comment]
Hi there,

Thank you for your interest in our work. Please be aware that the code should only be understood as a guideline for implementing the ideas presented in the book chapter (SSRN preprint).

Yes, agents are either long or short and don't switch sides.

Regarding the execution, the assumption is that every agent (coastline trader) is independent and doesn't interfere with the positions of other agents. If netting logic is required, you would have to implement that yourself.

Kind regards,
james

**Comment by pouet300** [comment]
Hello,

Many thanks for your reply.

Regards,
Pierre
