### ISSUE TITLE
Price change delta - linear vs. log

### ISSUE THREAD

**Issue by ko0f** [AntonVonGolub/Code#2]
In line 107, Runner calculates a `Math.log(price.elems.bid/extreme)` when price is a `PriceFeedData` object, while at line 164, the it's the same method except that it receives a price of type `double` and it performs a linear calculation of delta `price - extreme` instead the previous logarithmic calculation.

Why for an object price Runner uses a logarithmic calculation and for a double it performs a linear calculation of delta?

**Comment by himanshusanghi** [comment]
I have commented all the functions / constructors where price was of type double and have instead created a PriceFeedData object for the price.
This seems to work fine for me.
