### ISSUE TITLE
Runner.run() return values

### ISSUE THREAD

**Issue by ko0f** [AntonVonGolub/Code#3]
I assume that `Runner` is actually intrinsic events detector, while `run(price)` method updates the detector's state and returns the event detected, if any.

For return value, it seems that `0` stands for `No event`, `1 = Direction changed up`, `2 = Overshoot up`, `-1` and `-2` is the same only for down events.

If so, why in line 660, in `LocalLiquidity` does it return `2`, which is according to the above `Overshoot up`, when the closure it's in handles a `type == -1` (direction down)?

**Comment by VladUZH** [comment]
Though this notation is irrelevant (it's only important to know whether the observed event is DC or OS one) and is not used in the code, this notation can be a bit misleading. At the early stage of the work, two more liquidity indicators were used:  `upLiq` and `downLiq`. Now they are redundant.
