### ISSUE TITLE
The response rate is extremely low

### ISSUE THREAD

**Issue by himanshusanghi** [AntonVonGolub/Code#4]
Hi,

I tried running the above code on the USD-INR(indian rupee) data and the response rate is very low. I mean to say that it shows a couple of trades on some days and on some days, it shows no trades. So how frequently did the model show trades when you ran on other currencies.

Also, I am feeding the data day wise. At once I just send one day's tbt data and then in the next iteration , I send the next day's data but there is no connection between the previuos day's data to the next day's data. Is that how it is supposed to be. Or should I combine the data odf several days and then run the code.

Thanks.

**Comment by jbglattfelder** [comment]
Regarding your first observation, the choice of the directional change threshold sizes (and hence the overshoots) defines the frequency of events. As seen in Figure 3c in https://arxiv.org/pdf/0809.1040.pdf the number of directional changes can vary quite significantly across pairs (the axes are in log-scale). We have never analyzed USD/INR, but my guess would be to make the thresholds smaller.

Moreover, as seen in the lower panel of Figure 1 in https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2951348 the algorithm shows currency dependence, where not all crosses perform as well. Again this is linked to the directional-change frequency.

Hope this helps,
james

**Comment by himanshusanghi** [comment]
Thanks a lot for the answer !!!
I was able to increase the response rates by changing the deltas.
Could you please help with the second part as well?

**Comment by VladUZH** [comment]
The algorithm works only with tick-by-tick data, so the first tick of the next day is just one more price used by the Alpha Engine as an input parameter. You just need to have an array of all tick prices.
