### ISSUE TITLE
Do we keep positions overnight??

### ISSUE THREAD

**Issue by himanshusanghi** [AntonVonGolub/Code#5]
I have run the algorithm on the USD INR data and all the positions are not closed by the end of the day.
Is it supposed to be like this ? If not, is there anything special that needs to be done while transitioning between days. Or can we just treat the first point of the next day as the next point in the time series.

**Comment by VladUZH** [comment]
A position will be closed as soon as it is in the profit and it could take more than a day. 
The algorithm works only with tick-by-tick data, so the first tick of the next day is just one more price used by the Alpha Engine as an input parameter.
