### ISSUE TITLE
The Code.java is not worrking

### ISSUE THREAD

**Issue by tahuh** [AntonVonGolub/Code#7]
Hi

I have recently tried to use your Code.java but due to the imports I have difficult time to use this code.

There seems several Import/Annotation issue in current code and seems like you did not uploaded the cleaned code which is not using legacies.

For example, when I tried to use this code in Eclipse system with Windows OS, there are many "red lines".

It seems several classes for example Atom , AtomInput  or PriceFeedData and else are not implemented in this code.

I think it would be better if you implement all the requirements for this code in here(Code.java) or write some suggestions how to compile this code in Eclipse system or directly in Termianl(or command line prompt for Windows).

Or is there any chance that I can obtain those packages callsed "ch.olsen" ??

Lists are below ( directly copied and pased from your Code.java )

import ch.olsen.products.util.configuration.Configuration;
import ch.olsen.products.util.configuration.DoubleProperty;
import ch.olsen.products.util.configuration.EnumProperty;
import ch.olsen.products.util.configuration.StringProperty;
import ch.olsen.routes.atom.Atom;
import ch.olsen.routes.atom.AtomAbstr;
import ch.olsen.routes.atom.AtomException;
import ch.olsen.routes.atom.AtomInput;
import ch.olsen.routes.atom.AtomInputAbstr;
import ch.olsen.routes.atom.AtomOutput;
import ch.olsen.routes.atom.AtomOutputAbstr;
import ch.olsen.routes.atom.RoutesStep;
import ch.olsen.routes.cell.library.LibraryAutoDeploy;
import ch.olsen.routes.data.ArrayDataElement;
import ch.olsen.routes.data.DataElement;
import ch.olsen.routes.data.DataType;
import ch.olsen.routes.data.DoubleDataElement;
import ch.olsen.routes.data.NullDataElement;
import ch.olsen.routes.framework.RoutesFramework;

**Comment by jbglattfelder** [comment]
You should be able to get the code running as follows:

1. Remove all imports referencing ch.olsen.* and delete any resulting conflicting code.

2. Unfortunately, we cannot provide you with a tick feed. Hence, you need to implement your own code which handles the specific feed you want to use. This means you need your own PriceFeedData object dealing with it.

Hope this helps...
