### ISSUE TITLE
AntonVonGolub/Code The code is not working

### ISSUE THREAD

**Issue by kros235** [AntonVonGolub/Code#8]
Hi
Recently I downloaded a code from following URL
(https://github.com/AntonVonGolub/Code/blob/master/code.java) to run for research purpose.

I deleted several imports "ch.olsen~~~" unused imports
and joined with other library imports, by pressing "ctrl + shift + o" and selected the library related with 
'olsen'.

but i still have difficulties to run the code.
To illustrate, Main code is blank(empty) ,and also it seemed like some class definition codes are also missing.
(AtomInput,Atomabstr and so on). I assume this is the part of the project's code or some of the class definitions are included in ch.olsen library. Should I have to find external library file(ch.olsen~~) and import to the project to run this code?

Could you please tell how to proceed to run the code?
Thank you .

**Comment by jbglattfelder** [comment]
You should be able to get the code running as follows:

1. Remove all imports referencing ch.olsen.* and delete any resulting conflicting code.

2. Unfortunately, we cannot provide you with a tick feed. Hence, you need to implement your own code which handles the specific feed you want to use. This means you need your own PriceFeedData object dealing with it.

Hope this helps...

**Comment by Sajam** [comment]
@jbglattfelder - please stop saying (lying), that it's only matter of removing imports. I was doing it (making code work), but it's not just removing imports! It's rather:

- removing imports
- removing unused parts of the code
- reverse-engineering missing parts
- plus it's written extremely messy and hard to read/understand (I highly recommend https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882)
- it's not so easy, I bet more financial-oriented users wouldn't be able to do it

I can't publish working code due to NDAs, but you'd probably save some time on replying to such issues by publishing working code with documentation.

Hope this helps...

**Comment by jbglattfelder** [comment]
Dear @Sajam,

Let me first give you a bit of context to try and help you understand the situation.

We have fully disclosed all the inner workings of our trading model algorithm, described all the details, and also the history leading to the discoveries in https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2951348

To help people understand the ideas better, we provide some code here. Unfortunately, the trading model code is embedded in some legacy code. However, as the focus lies on the trading model algorithm and not the framework supporting it, we still thought it valuable to publish the code.

We are very sorry you got the impression that there would be no work involved on your side. As I mentioned in my reply under item 2: "...you need to implement your own code which handles the specific feed you want to use".

Finally, I am a bit puzzled that you would accuse me of lying. The first thee points you make referring to the code are precisely what I had written earlier.

In any case, please give us a bit of time to clean up the code.

Thank you for your interest in our work and for your understanding,
james

**Comment by Sajam** [comment]
@jbglattfelder - I do really appreciate your work -- especially, that you're sharing it with others. I wouldn't be able to came up with the code based on the paper itself. So I'm glad and thankful you've shared it. I also understand context and the fact, that the code is based on some legacy system.

> We are very sorry you got the impression that there would be no work involved on your side. As I mentioned in my reply under item 2: "...you need to implement your own code which handles the specific feed you want to use".

Yes - that information in the readme (or at least using different branch for not working code) would be helpful and save devs a lot of time.

> Finally, I am a bit puzzled that you would accuse me of lying. The first thee points you make referring to the code are precisely what I had written earlier.

I also referring to the other issues, I repeatedly getting an impression you're trying to prove, that this is trivial to run the code, when in fact it's not.

> In any case, please give us a bit of time to clean up the code.

That would be perfect!

Thanks,
Daniel
