### ISSUE TITLE
Unused code

### ISSUE THREAD

**Issue by chonkerboi** [AntonVonGolub/Code#9]
Hi!

I am porting you code to Python and was able to get most of it done.
One trouble I seem to have is with the Liquidity class. It looks like it is not used anywhere. Only the LocalLiquidity is used. Is that right and the Liquidity class can be safely removed or am I missing something?

**Comment by jbglattfelder** [comment]
You are right. Only LocalLiquidity() is relevant. The code has been updated and Liquidity() removed.
